name: Build Android APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev

    - name: Install Buildozer, Cython and Virtualenv
      run: |
        pip install --upgrade pip
        # اضافه کردن virtualenv که لینوکس گیت‌هاب به آن نیاز مبرم دارد
        pip install buildozer cython==0.29.36 kivy==2.3.0 pillow plyer virtualenv

    - name: Fix buildozer.spec requirements
      run: |
        sed -i 's/requirements = .*/requirements = python3, kivy==2.3.0, plyer, pillow/g' buildozer.spec

    - name: Build Android APK
      run: |
        # ساختن یک متغیر مجازی برای بویلدوزر تا در محیط خام گیت‌هاب گیج نشود
        export PATH=$PATH:~/.local/bin/
        yes | buildozer -v android debug
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: leprecoin-apk
        path: bin/*.apk
